services:
  samba-dc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lalilulelo_ad
    network_mode: "host"
    cap_add:
      - SYS_ADMIN
    environment:
      - REALM=LALILULELO.LOCAL
      - DOMAIN=LALILULELO
      - ADMIN_PASSWORD=datemi30!
    dns:
      - 127.0.0.1
    dns_search:
      - LALILULELO.LOCAL
    volumes:
      # Volumi nominali per salvare i dati di Active Directory e la configurazione
      - samba-etc:/etc/samba
      - samba-var:/var/lib/samba
    restart: unless-stopped
  ldap-ui:
    image: osixia/phpldapadmin:latest
    container_name: samba-ad-webui
    ports:
      - "8080:80"
    environment:
      # Modificato in ldaps:// per soddisfare il requisito "strong authentication"
      - PHPLDAPADMIN_LDAP_HOSTS=ldaps://192.168.1.201
      - PHPLDAPADMIN_HTTPS=false
    volumes:
      # Monta la configurazione LDAP personalizzata per ignorare il certificato self-signed
      - ./ldap.conf:/etc/ldap/ldap.conf:ro
    restart: unless-stopped


volumes:
  samba-etc:
  samba-var:

